### ISSUE TITLE
Css style is included after I remove the instruction to include it

### ISSUE THREAD

**Issue by rambip** [DioxusLabs/collect-assets#14]
**Problem**

When I include a stylesheet via manganis and I remove the import, the stylesheet is still used on the page.

**Steps To Reproduce**

1) create a file `test.css` with this content: `div {background-color: red;}`
2) create an empty dioxus project with this content:
```rust
#![allow(non_snake_case)]

use dioxus::prelude::*;
use manganis::*;

static _STYLE_SHEET: &str = mg!(file("test.css"));

fn App() -> Element {
    rsx!{
        div {
            "hello"
        }
    }
}

fn main() {
    launch(App)
}
```

3) launch with `dx serve`

The div is colored in red

4) comment the line `static _STYLE_SHEET: &str = mg!(file("test.css"));`

5) `dx serve` again

Now the div ist still red

**Expected behavior**

The div should return to default style when the line si commented out.

**Environment:**
 - Manganis version: v0.2.2
 - Rust version: 1.75.0
 - OS info: fedora
 - App platform: `web`

**Questionnaire**

- [ x] I'm interested in fixing this myself but don't know where to start

**Comment by jmmk** [comment]
At the very least, I would expect `dx clean` to remedy the situation, but it does not seem to. I was able to fix it only after finding https://github.com/DioxusLabs/dioxus/issues/2192 and cleaning up the files in `~/.cargo`

**Comment by ealmloff** [comment]
This was fixed in https://github.com/DioxusLabs/collect-assets/pull/30
