### ISSUE TITLE
CSS File Handling 

### ISSUE THREAD

**Issue by DogeDark** [DioxusLabs/collect-assets#22]
## Specific Demand

Currently, you can use manganis and CSS with something like:
```rs
const STYLE: &str = manganis::mg!(file("./style.css"));

fn Component() -> Element {
    rsx! {
        link {
            href: "{STYLE}"
            rel: "stylesheet",
            r#type: "text/css",
        }
    }
}
```
However, this isn't ideal as every time you use ``Component {}``, you are re-linking the CSS.

## Implement Suggestion

Provide a new ``mg!`` type for CSS files. At compile-time, append a ``link`` element with the CSS source to the ``head`` element in the ``index.html``

Preferably this could also support SCSS.

**Comment by ealmloff** [comment]
Currently if you build your application with the CLI, `manganis::mg!(file("./style.css"));` will add the css file to the head even if you never use the constant. That behavior may change if [a special head element is added](https://github.com/DioxusLabs/dioxus/issues/1169)

**Comment by DogeDark** [comment]
Hmm, it hasn't been following that behavior for me. I'll do some testing.

**Comment by DogeDark** [comment]
It does not work for examples (at least the single-file ones) e.g. ``dx serve --example preview``

**Comment by DogeDark** [comment]
Ok, it also doesn't work in workspaces. I'm gonna open a new issue for this
