### ISSUE TITLE
Manganis Fails to Provide Assets From Deps Unless `mg!` Is Used in App

### ISSUE THREAD

**Issue by DogeDark** [DioxusLabs/collect-assets#29]
**Problem**

Assets from dependencies aren't included in the final app unless the app itself uses the `mg!` macro.

**Steps To Reproduce**
- Create a library that uses ``mg!`` to include an asset.
- Create a binary that uses the dependency.
- Build with ``dx build`` and notice that no assets are included in ``dist/__assets_head.html`` or in the actual `<head/>` of the app.

**Expected behavior**

Assets from dependencies should be included.

**Environment:**
 - Manganis version: `0.2.2`
 - Rust version: `1.78`
 - OS info: `Windows 10`
 - App platform: `Any`

**Comment by ealmloff** [comment]
This was fixed in https://github.com/DioxusLabs/collect-assets/pull/30
